/**
 * 
 */
package com.blip.entity;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

/**
 * Entity Class responsible to keep the informations about the Purchase.
 * 
 * <i> ID is an incremental value generated by the DataBase.</i>
 * 
 * 
 * @author leomarques
 *
 */
public class Purchase {
	
	private Long id;
	private Calendar expires;
	private List<Details> purchaseDetails = new ArrayList<Details>();

	public Purchase(){
		
	}
	
	public Purchase addDetails(Details detail){
		purchaseDetails.add(detail);
		return this;
	}
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public Calendar getExpires() {
		return expires;
	}
	public void setExpires(Calendar expires) {
		this.expires = expires;
	}
	public List<Details> getPurchaseDetails() {
		return purchaseDetails;
	}
	public void setPurchaseDetails(List<Details> purchaseDetails) {
		this.purchaseDetails = purchaseDetails;
	}
	
	


}
